code --install-extension formulahendry.auto-close-tag
code --install-extension steoates.autoimport
code --install-extension formulahendry.auto-rename-tag
code --install-extension aaron-bond.better-comments
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension rangav.vscode-thunder-client
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscode-styled-components
